### ISSUE TITLE
ProductName-Swift doesn't contains LTMorphingLabel method?

### ISSUE THREAD

**Issue by FFFang** [lexrus/LTMorphingLabel#102]
Hi,man.
我的操作步骤是这样的：
1.建立一个新的OC项目。
2.手动导入LTMorphingLabel。
3.开启混编（生成ProductName-Swift.h）
此时在文件中没有出现LTMorphingLabel对应的OC方法，可否help一下？

**Comment by FFFang** [comment]
Xcode9，拖拽库进项目的话，不会生成对应Swift方法。右键项目add files的话，会生成对应Swift方法。

**Comment by Sky0372Lsk** [comment]
OC调用不了这个属性：var morphingEffect: LTMorphingEffect = .scale  暂时还是没有实现
