### ISSUE TITLE
Unknown class LTMorphingLabel in Interface Builder file.

### ISSUE THREAD

**Issue by hbshih** [lexrus/LTMorphingLabel#112]
Hi,

Does anyone got the same error message when using this library in Swift 4, iOS 10+?

I got 

> Unknown class LTMorphingLabel in Interface Builder file.

When running the following code:

import LTMorphingLabel
class WelcomePageViewController: UIViewController,LTMorphingLabelDelegate 
{
    @IBOutlet weak var welcomeText: LTMorphingLabel!
    override func viewDidLoad() {
        super.viewDidLoad()
        welcomeText.delegate = self
        welcomeText.morphingEnabled = true
        welcomeText.morphingDuration = 3.0
        welcomeText.morphingEffect = effect
    }
}

**Comment by Co2333** [comment]
Xcode is a forking piece of shiiiit while I'm thinking about code errors.
Clean, exit, quiet xcode, reboot, restart.
Then you will see something like this:
![image](https://user-images.githubusercontent.com/25259084/47926005-77ecd480-defa-11e8-8ae4-eb2d26be938a.png)

**Comment by gmckee1** [comment]
Make sure that in your Storyboard, you are setting the Module to LTMorphingLabel (image below). This solved the problem for me.

<img width="246" alt="screenshot 2019-01-25 at 21 21 40" src="https://user-images.githubusercontent.com/5838168/51773623-51000200-20e7-11e9-9328-ed47d0562e5f.png">
