### ISSUE TITLE
Possibility to update the framework to **SWIFT 4.2**

### ISSUE THREAD

**Issue by El-Buritos** [lexrus/LTMorphingLabel#116]
I recently update my code to the last swift version and the LTMorphingLabel framework do not work now.

One of the errors : 

`Cannot assign value of type 'CAEmitterLayerEmitterMode' to type 'CAEmitterLayerRenderMode'`

at this line 

`layer.renderMode = CAEmitterLayerEmitterMode.outline`

or other like : 

`Cannot assign value of type 'CAEmitterLayerEmitterMode' to type 'CAEmitterLayerRenderMode'`

at this line : 

`layer.renderMode = CAEmitterLayerEmitterMode.surface`

Thanks for your reply if any have a solution !

**Comment by lexrus** [comment]
It's fixed in #115. You may try the latest HEAD. I'll tag a new version once everthing is done.
Thanks.

**Comment by El-Buritos** [comment]
Thanks for your quick solution !
