### ISSUE TITLE
+6000 stars - two lines of instructions

### ISSUE THREAD

**Issue by mosn** [lexrus/LTMorphingLabel#117]
Thanks very much for your contribution,

Please provide a few  instructions to help fellow developers who wants to use this.I could not get this to work otherwise would gladly make a PR

**Comment by lexrus** [comment]
Hi, @mosn,
I'm bad at English writing, sorry for the lack of documentation. But it's straightforward to use modern package management tools such as Carthage and CocoaPods to install this lib. And it's not recommended to install it manually. Feel free to specify any necessary process that I missed in the README.

Thanks.
