### ISSUE TITLE
Float to Int conversion error in LTMorphingLabel.swift

### ISSUE THREAD

**Issue by Fadedglyph** [lexrus/LTMorphingLabel#123]
It's fine when the app launches. The slider scales it properly. But as I'm tapping on the label itself or clicking on the UISegmentedControl, it's crashing because the compiler can't convert the value to int because `either it's infinite or NaN`. I am attaching a screenshot, please look into this and let me know what to do.
PS: I direct downloaded it from GitHub.
![screen shot 2019-01-16 at 12 13 00](https://user-images.githubusercontent.com/33647367/51231033-1a5c1600-1988-11e9-9101-112de857bcf8.png)

**Comment by lexrus** [comment]
Thanks, it's fixed.
