### ISSUE TITLE
Lags in the animation

### ISSUE THREAD

**Issue by yura-voevodin** [lexrus/LTMorphingLabel#124]
Lags in the animation on the latest version 0.6.0.

![ltmorphinglabel 0 6 0 2019-01-30 15_28_42](https://user-images.githubusercontent.com/2790873/51984440-00e8bd00-24a4-11e9-95af-84476cf9a9a0.gif)

And on 0.5.9 version of the library everything was ok.

![ltmorphinglabel 0 5 9](https://user-images.githubusercontent.com/2790873/51984460-09d98e80-24a4-11e9-875d-f80e08868b51.gif)

My class `AnimatedLabel` added via Storyboard.

```
import LTMorphingLabel
import UIKit

class AnimatedLabel: LTMorphingLabel {
  
  required init?(coder aDecoder: NSCoder) {
    super.init(coder: aDecoder)
    
    morphingEffect = .evaporate
    morphingDuration = 0.7
  }
}
```

**Comment by lexrus** [comment]
Thank you. I'll add a test case for this today.

**Comment by yura-voevodin** [comment]
@lexrus And one important thing. On Simulator everything is OK. Lags appears only on device.

**Comment by lexrus** [comment]
@yura-voevodin Please check out the master branch. I just updated the demo with a progress control. And increased the total frame count. Could you also give the numbers of `morphingDuration` and `morphingCharacterDelay` so that I can reproduce the issue on my iPhone.

**Comment by ownmas** [comment]
Same issue. Video: https://drive.google.com/file/d/1pq7Tven49KUxgjgdLAGCGrxjsEJl_Nay/view?usp=drivesdk

You may download my app and see that issue: https://itunes.apple.com/us/app/repost-for-instagram-quick-ig/id1445207836

**Comment by ownmas** [comment]
I updated to latest commit and the problem is solved. Thank you!
`pod 'LTMorphingLabel', :git => 'https://github.com/lexrus/LTMorphingLabel.git', :commit => '757ed4c'`

**Comment by yura-voevodin** [comment]
@lexrus Works fine on the latest commit! I'm using `morphingDuration = 0.7` and `morphingCharacterDelay` with default value.

**Comment by marclefrancois** [comment]
Would be nice if you did a Cocoapods release with the lag fix, Thanks
