### ISSUE TITLE
Incomplete display

### ISSUE THREAD

**Issue by langyan1022** [lexrus/LTMorphingLabel#128]
When I used LTMorphingLabel at the time, I often showed the picture on the view first display.
![image](https://user-images.githubusercontent.com/5259422/56888563-e45e2000-6aa6-11e9-8b4d-48bfcc0a25c4.png)
The red line on the picture is surrounded by two, the display is incomplete, and one is not displayed.
These three values may not change so fast.
But the initial value is empty, I tracked to use label.text to set the value.

I am using the LTMorphingEffect.sparkle effect.

**Comment by lexrus** [comment]
Please add a minimum height constraint to the label.
