### ISSUE TITLE
How to export video or LTMorphingLabel insert to a video?

### ISSUE THREAD

**Issue by CoTMMO** [lexrus/LTMorphingLabel#133]
Hi all, i just find the solution for export video or LTMorphingLabel insert to a video
Anyone could help me or any ideas are welcome.
Thanks all very much!

**Comment by amrittrivedir** [comment]
@CoTMMO  - Have you found solution?

**Comment by lexrus** [comment]
The key is:
1. Use a green background, which you can key the green with After Effects or DaVinci Resolve
2. Record the video with your iPhone
