### ISSUE TITLE
Times New Roman Font on iOS-13 (Xcode-11)

### ISSUE THREAD

**Issue by s-ahmad88** [lexrus/LTMorphingLabel#134]
I am facing a weird issue after updating to XCode-11. 
Only on the devices with iOS-13 the the font appears to be as TIMES NEW ROMAN. whereas on devices having older versions the font seems to be perfectly fine.

Any help anyone please?

![Screen Shot 2019-10-31 at 9 24 36 am](https://user-images.githubusercontent.com/4697283/67903654-46b3ec80-fbc0-11e9-87f5-0627aa9b8126.png)

**Comment by alihanaktay** [comment]
I've faced same issue. You can set textAttiributes to label like below. It's working.

` label.textAttributes = [NSAttributedString.Key.font: UIFont.systemFont(ofSize: 17, weight: .semibold)]
`

**Comment by Co2333** [comment]
> I've faced same issue. You can set textAttiributes to label like below. It's working.
> 
> `label.textAttributes = [NSAttributedString.Key.font: UIFont.systemFont(ofSize: 17, weight: .semibold)]`

yep it works, but how can I resolve this new problem?

-> The text is like being cut by some hard stuff

![Screen Shot 2020-02-21 at 上午7 48 30](https://user-images.githubusercontent.com/25259084/74990588-a63f4c00-547e-11ea-822a-a551c985e4d7.png)
