### ISSUE TITLE
Help!!! Why I got this? Error: this application, or a library it uses, has passed an invalid numeric value (NaN, or not-a-number) to CoreGraphics API and this value is being ignored. Please fix this problem.

### ISSUE THREAD

**Issue by uuuuue** [lexrus/LTMorphingLabel#135]
Error: this application, or a library it uses, has passed an invalid numeric value (NaN, or not-a-number) to CoreGraphics API and this value is being ignored. Please fix this problem.

**Comment by lexrus** [comment]
I can't address this issue without any context.
