### ISSUE TITLE
delegate method morphingDidStart is not being called

### ISSUE THREAD

**Issue by dogeri28** [lexrus/LTMorphingLabel#140]
all other delegate methods are being call apart from morphingDidStart

**Comment by lexrus** [comment]
<img width="571" alt="Screen Shot 2020-09-20 at 4 38 03 PM" src="https://user-images.githubusercontent.com/219689/93707304-a9f39800-fb5f-11ea-92c3-e8c0b2c779c4.png">
Um... how can I reproduce the problem? Any specific settings?

**Comment by lexrus** [comment]
I just close this issue for now. Please feel free to reopen it once you have further questions.
