### ISSUE TITLE
CocoaPods and Carthage

### ISSUE THREAD

**Issue by lexrus** [lexrus/LTMorphingLabel#21]
I knew CocoaPods is now compatible with Swift libs. And there is also another awesome option made by GitHub.
I'd like to support both.

**Comment by skywinder** [comment]
+1 cocoapod please!

**Comment by syrakozz** [comment]
+1 cocoapod

**Comment by lexrus** [comment]
It's now compatible with Carthage.
I'll create a new spec for CocoaPods later today.

**Comment by lexrus** [comment]
@skywinder @syrakozz 
Please try:
``` ruby
pod 'LTMorphingLabel', '~> 0.0.3'
```
