### ISSUE TITLE
我发现在4s设备有些卡顿

### ISSUE THREAD

**Issue by K-cat** [lexrus/LTMorphingLabel#22]
效果是非常炫的，我在iOS7 4s调试上发现非常占用CPU，比较卡顿，请问有什么解决方案么？谢谢

**Comment by lexrus** [comment]
你可以试着降低帧数，改一下 _displayFrameTick 这个方法。
另外，理论上，使用 SpriteKit 效率会更高，CPU 占用也更低。

**Comment by K-cat** [comment]
确实改了帧数就好了一些，谢谢，但是确实有点占用CPU，但是真的非常喜欢这种效果，初入开发，就能够接触到这么牛的效果，我是OC和Swift混编的，应该没有什么影响吧

**Comment by lexrus** [comment]
如果你用了那几个粒子动画效果的话，可以适当减少喷发量，或者降低素材分辨率，也能提高性能。
用 Swift 的话最终项目会多一个运行时，包会大一点，其它没什么影响。

不过上面提到的这些问题会随着硬件更新换代自动解决，我觉得可能不需要花时间解决，请原谅。
