### ISSUE TITLE
LTMorphingLabel undeclared identifier

### ISSUE THREAD

**Issue by Nerkyator** [lexrus/LTMorphingLabel#25]
Hi!
I'm new to cocoapods so maybe is my fault...but...
I have a problem running LTMorphingLabel.
I installed it following your instructions
* gem install cocoapods --pre
* Added this line to my Podfile: pod 'LTMorphingLabel', '~> 0.0.3'
* Installed the pod: pod install

Everything goes fine (CMD + u too)
But when I change class from UILabel to LTMorphingLabel I have an Xcode error saying "Use of undeclared identifier LTMorphingLabel".

I noticed frameworks links in red in the Pods -> Framework -> iOS folder so I relinked them, but nothing changes...

Environment

* OS X 10.10.2
* Xcode 6.1.1
* cocoapod 0.36.0.beta.1

(Git demo works like a charm)

Thank you!

**Comment by Nerkyator** [comment]
I'm a noob -_-
completely forgot to **import LTMorphingLabel**
I'm sorry...you can close this "issue"

Thanks!

**Comment by lexrus** [comment]
Never mind.
I've just tested in a fresh project and everything works fine.
