### ISSUE TITLE
Thank you so much for this project !

### ISSUE THREAD

**Issue by moheny** [lexrus/LTMorphingLabel#26]
Thank you so much for this project and for doing it in swift.
however, I'm unable to use it and I don't understand what's wrong my code.
I've declared the outlet as
 @IBOutlet var label: LTMorphingLabel!
then setting the text as
        label.morphingEffect = .Scale
        label.center = CGPointMake(160, 284)
        label.text = "I'am a test label"
        self.view.addSubview(label)
but for some reason the text doesn't change, plus I can't seem to run your project on simulator. it's successfully finish to load it, but nothing appear on simulator. thank you very much for any help .

**Comment by lexrus** [comment]
It's unnecessary to addSubview(label) while you are using IBOutlet to connect to the existing label in your Xib or storyboard.

**Comment by moheny** [comment]
Thank you for the quick answer, Matter of fact I trying to add it without and IBOutlet, cause i'm writing everything programatically. 
       var label = LTMorphingLabel(frame: CGRectMake(0, 0, 200, 21))
        label.morphingEffect = .Scale
        label.text = "I'am a test label"
        self.view.addSubview(label)

this code not working either.

**Comment by lexrus** [comment]
The label must be insert into the view hierarchy before animating any properties. So you'd better move the addSubview method up.
``` swift
let label = LTMorphingLabel()
label.frame = CGRectMake(50, 100, 300, 20)
view.addSubview(label)
label.text = "I'am a test label"
```

**Comment by moheny** [comment]
Yup it’s working now, I didn’t figure out I need to set the Label to different value before the effect occur.
Thank you so much for you help,
god bless you.
