### ISSUE TITLE
App crashes when getting or setting the text property

### ISSUE THREAD

**Issue by arbitur** [lexrus/LTMorphingLabel#28]
I installed this by just dragging in the LTMorphingLabel folder (I firstly installed with cocoapods but it got messed up so I removed it).

I just followed the instructions under Usage and added a UILabel in storyboard and link it with `@IBOutlet` and changed its class to `LTMorphingLabel`
 ```Swift
@IBOutlet var lbl:LTMorphingLabel!
```

I get no error message or anything, it just breaks at the line where I either try to print out its text or when I try to set its text.

Im using xcode 6.2 and swift 1.1

**Comment by lexrus** [comment]
Hi, Philip,

What’s the error message?
If you don’t know how to check it, you can send me the project.

B.T.W. You may have a look at my LTMorphingLabelDemo target which just works fine within a storyboard.

Thanks.

-- 
Lex Tang
Sent with Airmail

On March 15, 2015 at 6:46:42 PM, Philip (notifications@github.com) wrote:

I installed this by just dragging in the LTMorphingLabel folder (I firstly installed with cocoapods but it got messed up so I removed it).

I just followed the instructions under Usage and added a UILabel in storyboard and link it with @IBOutlet and changed its class to LTMorphingLabel

@IBOutlet var lbl:LTMorphingLabel!

**Comment by lexrus** [comment]
No reply for 10 days, I assume it's fixed. Feel free to reopen it if anything I can help.
