### ISSUE TITLE
Why I can't run your demon in Xcode 6.2 and 6.3 ?

### ISSUE THREAD

**Issue by lmcmz** [lexrus/LTMorphingLabel#29]
Sorry, I'm a beginner in iOS.
Recently I'm doing a project for practice 
but there is a error confuse me why there're a lot of code which I found in GitHub.
Can't run in my Xcode.
:-(
By the way, I'm also a Chinese.
![2015-03-17 7 37 21](https://cloud.githubusercontent.com/assets/9669733/6701064/1096af46-ccdd-11e4-82de-77c95dc97562.png)

**Comment by lexrus** [comment]
The `master` branch is compatible with Xcode 6.2 which comes with Swift 1.1. You can check your compiler with:
```xcode-select -p```
And select the stable version with:
```sudo xcode-select -s /Applications/Xcode.app/Contents/Developer```

**Comment by lmcmz** [comment]
Figure it out , :)
Thanks so much !
