### ISSUE TITLE
Use this Lib in OC Project

### ISSUE THREAD

**Issue by Jasonbroker** [lexrus/LTMorphingLabel#30]
Hi man!

Thanks for your job!

请问在OC 项目中如何设置效果？
`.morphingEffect` 在OC 中无法访问，且在Xcode自动生成的头文件中没有看到这个枚举选项。

多谢帮助。

**Comment by lexrus** [comment]
这个 bug 最多还能活一两个月，因为在 Xcode 6.3 里可以用 `@objc` 修饰符让 Objective-C 也能使用 Swift 的 enum。让我们耐心等待正式版吧。
![screen shot 2015-03-24 at 9 27 38 pm](https://cloud.githubusercontent.com/assets/219689/6802578/ba1d3a00-d26c-11e4-97f7-d696a1bcc97c.png)
