### ISSUE TITLE
♥️ Apps using LTMorphingLabel

### ISSUE THREAD

**Issue by lexrus** [lexrus/LTMorphingLabel#32]
I would appriciate it if you tell me that your App is using LTMorphingLabel. Your shinny app may encourage me to make this lib better. And I'll list your App in the README.

Thanks.

**Comment by lexrus** [comment]
Although it's not production ready yet, do you have any App using this lib?
@jasonbroker @arbitur @EzimetYusup @alariccole @alariccole @kenhama @mxcl @Imcmz @moheny @Nerkyator @37to @raychrd @K-cat @HughJia @shnhrrsn @DingSoung @lazerwalker @zzndino @skware @zzz6519003 @MichMich @eriktelepovsky @alexrmacleod @tobbe01

**Comment by shnhrrsn** [comment]
Unfortunately not shipped yet, but the welcome screen for my app is built pretty heavily around LTMorphingLabel.  If you're interested in seeing it in action, DM me your email and I'll get you on our TF beta.

**Comment by lexrus** [comment]
@shnhrrsn I'm interested in it. Please: lexrus@gmail.com

**Comment by lazerwalker** [comment]
My app [The Met Challenge](https://itunes.apple.com/us/app/the-met-challenge/id917662781) is using it.

**Comment by alexbtlv** [comment]
My app [Postys - Video Digest](https://itunes.apple.com/app/id989570652) use it. Those counter numbers on background is also LTMorphingLabel 😀

**Comment by zzz6519003** [comment]
can u explain the principle of the magic in one sentence XD

2015-07-12 5:18 GMT+08:00 Alexander <notifications@github.com>:

> My app Postys - Video Digest <https://itunes.apple.com/app/id989570652>
> use it. Those counter numbers on background is also LTMorphingLabel 😀
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lexrus/LTMorphingLabel/issues/32#issuecomment-120662143>
> .
>



-- 

yours,

正中赵
about.me/zzz6519003
[image: 正中赵 on about.me]
  <http://about.me/zzz6519003>

**Comment by lexrus** [comment]
Moved into a WiKi page so that everyone can edit it.
https://github.com/lexrus/LTMorphingLabel/wiki/Apps-using-LTMorphingLabel
