### ISSUE TITLE
Default rendering in Interface Builder

### ISSUE THREAD

**Issue by DanielAsher** [lexrus/LTMorphingLabel#34]
Currently LTMorphingLabel does not render in a storyboard or xib

**Comment by lexrus** [comment]
Please check out the latest source code. I just fixed some layout issues.

![screen shot 2015-04-24 at 12 10 40 pm](https://cloud.githubusercontent.com/assets/219689/7312302/24f8ea10-ea7b-11e4-9fdb-cb2234bb1e3d.png)

**Comment by DanielAsher** [comment]
wonderful!
