### ISSUE TITLE
It seem there is a issue of the line breaks.

### ISSUE THREAD

**Issue by lmcmz** [lexrus/LTMorphingLabel#35]
I try to configure it as a normal UILabel.
But it's not feasible.
Then I make a testLable above it.
The normal UILable works but LTMorphingLabel not.
:(
![ios simulator screen shot 2015 4 17 12 21 33](https://cloud.githubusercontent.com/assets/9669733/7207113/bc53ab36-e4fc-11e4-9e9a-a6f428c4144b.png)

**Comment by lexrus** [comment]
I'm sorry, multiline support is not ready. #17

**Comment by lmcmz** [comment]
No, :)

**Comment by lmcmz** [comment]
No, It's fine.

**Comment by lmcmz** [comment]
No, your project is pretty.
I'll figure it out.
Thanks so much for opening source.
:)
