### ISSUE TITLE
Make public properties @IBInspectable

### ISSUE THREAD

**Issue by ndmeiri** [lexrus/LTMorphingLabel#37]
Hi, great component so far! Having access to the following properties at design time would be very helpful and would cut down on boilerplate code to use this control:
```Swift
public var morphingProgress: Float
public var morphingDuration: Float
public var morphingCharacterDelay: Float
public var morphingEffect: LTMorphingEffect
```

I believe we could implement this just by marking these properties as `@IBInspectable`. Do you think there's anything else we'd have to do?

**Comment by lexrus** [comment]
Thank you @ndmeiri .

I don't know how does IB present enum properties. I gonna have a try.

**Comment by lexrus** [comment]
As I expected, the morphingEffect enum can not be configured via IB.

![screen shot 2015-06-16 at 12 00 16 pm](https://cloud.githubusercontent.com/assets/219689/8175602/4d77ed10-141f-11e5-8b39-f99887003525.png)

Did I miss something?
