### ISSUE TITLE
Should LTMorphingEffect's allValues be public?

### ISSUE THREAD

**Issue by callmewhy** [lexrus/LTMorphingLabel#41]
Maybe I can't use `allValues` in `LTMorphingEffect`. Should this be public?
```
@objc public enum LTMorphingEffect: Int, Printable {
    ...    
    static let allValues = ["Scale", "Evaporate", "Fall", "Pixelate", "Sparkle", "Burn", "Anvil"]
    ...
}
```

**Comment by lexrus** [comment]
You don't have to. `allValues` is just a well known solution for enumerating values in enum type in Swift.
https://www.google.co.jp/search?q=enumerate+enum+values+swift

**Comment by callmewhy** [comment]
Yes, I want to enumerate values in enum type but don't have access to `allValues`。

**Comment by lexrus** [comment]
Fixed in the latest release.
