### ISSUE TITLE
How to disable the text effect when init?

### ISSUE THREAD

**Issue by neil-wu** [lexrus/LTMorphingLabel#42]
When my view first loaded, I want to set some value for the label without effect animation. 
How to make it? 

```self.upNumTxt.text = "init val"```

Any suggestions ? Thx

**Comment by lexrus** [comment]
You can temporarily set morphingDuration to 0.001 and reverse to the default value 0.6 once you need the animation.
I should add an morphingEnabled property in the next release.

**Comment by neil-wu** [comment]
thx.

**Comment by lexrus** [comment]
Please checkout the latest release(0.0.9) and try the morphingEnabled property.

**Comment by neil-wu** [comment]
Well done. :+1:
