### ISSUE TITLE
Temporary disable animations

### ISSUE THREAD

**Issue by borut-t** [lexrus/LTMorphingLabel#43]
Is is possible to disable animations on/off?
It would be nice cos I don't want animations when I initially set text.

Thanks!

**Comment by lexrus** [comment]
Duplicate as #42
There should be a on/off property in the next release.

**Comment by borut-t** [comment]
@lexrus Is any release date set regarding this new feature?

**Comment by lexrus** [comment]
Please checkout the latest release(0.0.9).
