### ISSUE TITLE
Image not found

### ISSUE THREAD

**Issue by honghaoz** [lexrus/LTMorphingLabel#44]
I used CocoaPod to integrate LTMorphingLabel,

When I was using style 
```swift
label.morphingEffect = .Anvil
```

I got `fatal error: unexpectedly found nil while unwrapping an Optional value`

This line caused crash
```swift
let image = UIImage(named:"Sparkle")!.CGImage
```

"Sparkle" image was not found. But I saw the image in Resource folder.

**Comment by lexrus** [comment]
Please check out the latest release(0.0.9).

**Comment by honghaoz** [comment]
@lexrus Cool, thanks! :+1:
