### ISSUE TITLE
Resources not accessible when using frameworks

### ISSUE THREAD

**Issue by craiggrummitt** [lexrus/LTMorphingLabel#45]
The resources folder(needed by Sparkle, Burn and Particle) doesn't seem to be accessible with use_frameworks in CocoaPods. If you drag the resources folder from the LTMorphingLabel pod into your project, it works ok. Not sure if there's a better approach. This should however be mentioned probably in the readme.

**Comment by lexrus** [comment]
Hi Craig,
This issue was fixed in #44 . Please try the latest version(0.0.9).

**Comment by craiggrummitt** [comment]
I was using latest version, and the issue you linked to looks like a different issue.

**Comment by lexrus** [comment]
@craiggrummitt I'm sorry I made a mistake in #44. And it's fixed via https://github.com/lexrus/LTMorphingLabel/commit/7f7c2ae11ce430a0c720154f64d7f56dc657309b
I've tested it in a empty project with CocoaPods when use_frameworks enabled.
Please check out version 0.1.0.
Thanks.
