### ISSUE TITLE
Emoji Support

### ISSUE THREAD

**Issue by joshuawright11** [lexrus/LTMorphingLabel#47]
There seem to be issues in animations with emojis... they pop up twice or aren't properly removed. 

e.g. "Fire 🔥" morphed to "Zap⚡️" will result in "Zap " with a 🔥 and ⚡️ on top of each other.  Is there a workaround for this?

I recognize that the amount of people using this library for emojis is probably minuscule, but still would be cool if there were an easy fix. 

Love the library so much! Thanks for all your hard work!

**Comment by lexrus** [comment]
An emoji will be rendered with a default size when I set the fontSize to 0 which may be a invalid size I guess. I fix it by limiting the minimum size to 0.001.
Please check the latest code. I'll release a new version sooner or later.

**Comment by lexrus** [comment]
Please check out 0.1.1.

**Comment by joshuawright11** [comment]
Sweet! Thanks so much 😃
