### ISSUE TITLE
Use of undeclared type 'LTMorphingLabel'

### ISSUE THREAD

**Issue by moheny** [lexrus/LTMorphingLabel#50]
First of all, let me start by saying I love this project !
I have a project with 5-6 pods working on it, lately I've added this pod as well.
everything find when i'm adding label on storyboard and setting it to LTMorphingLabel.
The problem start when i'm trying to connect the label to code:
 @IBOutlet private var label: LTMorphingLabel!
i'm getting this error, Use of undeclared type 'LTMorphingLabel'.
I've tried to import LTMorphingLabel class but it's not recognise as well, of course i've tried to close the project and clean it. did it happen to any of you ? is there any solution for this ? thank you so much. god bless.

**Comment by lexrus** [comment]
Did you open the xcworkspace?

**Comment by moheny** [comment]
Thank you for the quick answer, of course i'm using the the xcWorkSpace, as I said I have pods working already with it... i'll try to manually add the library.

**Comment by lexrus** [comment]
Hay moheny,
Could you send me your project files?
lexrus@gmail.com

**Comment by exedmg** [comment]
Hi @lexrus , I face the exact same problem with @moheny. Could you please share the solution for this problem? Thanks.

**Comment by moheny** [comment]
I've wrote the solution. Add the framework Manually, then when change the module inside the inspector.

**Comment by lexrus** [comment]
Thank you @moheny .
I gonna check it again tonight.

**Comment by exedmg** [comment]
Thank you very much @moheny for the help.

**Comment by pkasson** [comment]
I had the same issues as above ... and after adding the project manually, had the same error:

"Unknown class _TtC15LTMorphingLabel15LTMorphingLabel in Interface Builder file."

I am changing the IB setup as described by removing the module to see if that fixes it.

**Comment by Hey-Scotty** [comment]
you can also write the import in the head in this format : 
import Pods_YourAppName
import LTMorphingLabel
