### ISSUE TITLE
pod update gives error in LTMorphingLabel.swift

### ISSUE THREAD

**Issue by Jackson0111** [lexrus/LTMorphingLabel#52]
I did pod update, and received this error: 
![screen shot 2016-03-30 at 5 01 18 pm](https://cloud.githubusercontent.com/assets/13260808/14157477/2f972c0e-f699-11e5-9d5c-ca1b42bd2e76.png)

It looks like something is wrong with the selector, but i tried several ways to fix this, didn't work.

**Comment by lexrus** [comment]
Please check the version of your Xcode. LTMorphingLabel 0.2 requires the latest 7.3 to compile.

**Comment by Jackson0111** [comment]
Got it, updating now. Thanks!

**Comment by lexrus** [comment]
Thanks. There would be a lot of warnings after the upgrade. Good luck.

**Comment by Jackson0111** [comment]
A lot of warnings in LTMorphingLabel or in everything?

**Comment by lexrus** [comment]
If you used Selectors in your project, you'd probably refactor them to the latest syntax by hand. I just spent 2 hrs to do that in one of my project last week.

**Comment by Jackson0111** [comment]
Yep...I just updated and saw it...
