### ISSUE TITLE
Problem on showing 0 (zero) in the label, Swift 2.2 and Xcode7.3

### ISSUE THREAD

**Issue by mjhassan** [lexrus/LTMorphingLabel#54]
After updating my project to Swift 2.2 in xcode 7.3 none of the following code showing 0 (zero) in the label.

    myMorphingLabel.text = "0"
Or

    let zeroValue = 0
    myMorphingLabel.text = String(zeroValue)
    myMorphingLabel.text = String(format: "\(zeroValue)")

But if I try with 1 or 0.0, it works.
Can please check this? Thanks.

**Comment by lexrus** [comment]
How do you install this lib? CocoaPods or Carthage?

**Comment by lexrus** [comment]
I just publish the latest version. Please upgrade and try again.
