### ISSUE TITLE
Missing argument for parameter 'selector' in call

### ISSUE THREAD

**Issue by david-koch-pro** [lexrus/LTMorphingLabel#55]
![screen shot 2016-05-24 at 09 41 02](https://cloud.githubusercontent.com/assets/16528614/15496125/e9795ce4-2193-11e6-9cec-0056a5f39867.png)

**Comment by lexrus** [comment]
Please upgrade your Xcode to 7.2.1+

**Comment by david-koch-pro** [comment]
Thank you
