### ISSUE TITLE
Label does not show after view is loaded

### ISSUE THREAD

**Issue by thedc89** [lexrus/LTMorphingLabel#59]
When my view is loaded, label is not visible. Only after certain action is taken to change label's text, label finally shows up.

Maybe there is something speciffic with configuration parameters that hides my label, I don't know. When I change my label's class to regular UILabel, it is visible, so there must be something with the LTMorphingLabel class itself.

**Comment by thedc89** [comment]
For some reason cocoapods installation didn't take into account your last commit, where you had fixed this issue.

**Comment by lexrus** [comment]
Thank you for your remind. I've published the latest version to CocoaPods trunk.
