### ISSUE TITLE
Changing the font size causes the label's text to stretch out or compress

### ISSUE THREAD

**Issue by Sweeper777** [lexrus/LTMorphingLabel#62]
Originally, the label looks like this:

<img width="319" alt="screen shot 2016-07-30 at 11 05 08 am" src="https://cloud.githubusercontent.com/assets/13585047/17267804/fa05cd22-5645-11e6-9413-5f54ecb0f58e.png">

After setting the font size using:

    label.font = UIFont.systemFontOfSize(16)

It becomes this:

<img width="318" alt="screen shot 2016-07-30 at 11 05 28 am" src="https://cloud.githubusercontent.com/assets/13585047/17267808/12002224-5646-11e6-80ef-13fcff2856ac.png">

The spacing between the characters are all messed up.

**Comment by lexrus** [comment]
Fixed in https://github.com/lexrus/LTMorphingLabel/commit/624651164c63c61e16c810a856ef2f4f4bb8889a

**Comment by Sweeper777** [comment]
Thanks :)
