### ISSUE TITLE
Version 0.3.0 with Pods

### ISSUE THREAD

**Issue by daramoni** [lexrus/LTMorphingLabel#66]
![screen shot 2016-09-12 at 4 27 01 p m](https://cloud.githubusercontent.com/assets/5332057/18453645/e8f20806-7905-11e6-81cc-5d2923783121.png)

how to use the version 0.3.0 with pods?

**Comment by lexrus** [comment]
Hi @daramoni 
It's fixed. Please try again.

**Comment by daramoni** [comment]
Ready!, thanks
