### ISSUE TITLE
Swift 3.0

### ISSUE THREAD

**Issue by moiseevanton** [lexrus/LTMorphingLabel#70]
Hey there, just wanted to know when this API will be updated to Swift 3.0? Thanks!

**Comment by lexrus** [comment]
Hi @moiseevanton,

There is already a swift3 branch in this repo. I'll switch the master branch to 3.0 soon.

**Comment by Sweeper777** [comment]
Can you tell me what to write in the podfile in order to install the swift 3 branch?

**Comment by moiseevanton** [comment]
pod ‘LTMorphingLabel’, :git => ‘https://github.com/lexrus/LTMorphingLabel.git’, :branch => ‘swift3’
