### ISSUE TITLE
Update to Swift3 version issue

### ISSUE THREAD

**Issue by jinfagang** [lexrus/LTMorphingLabel#76]
As the Swift3 becomes a more wide and seems have no big change, strongly recommend author update this excellent library to Swift3.

**Comment by gitIkerKristian** [comment]
When you install latest version LTMorphingLabel (0.3.0), and convert it to Swift 3.0 (Edit -> Convert -> To Current Swift Syntax...), XCode will create 2 build errors:
_Expression type 'Array<Any>' is ambiguous without more context_

File: LTStringDiffResult.swift
Lines: 40 and 52

Quick and easy solution is to remove "<Any>" and "as! [LTCharacterDiffResult]" from those 2 lines.

**Comment by lexrus** [comment]
The master branch is upgrade to Swift 3. You can upgrade to the latest release.
Thanks.
