### ISSUE TITLE
Text alignment is strange on IOS 8 

### ISSUE THREAD

**Issue by skware** [lexrus/LTMorphingLabel#8]
Hi,

Congrats for this label, it's very cool.
I have a problem. Everything displays properly centered on IOS 7 but is offsetted to the right on iOS 8 .
Do you have an idea?

Thanks

**Comment by lexrus** [comment]
@skware 
I've activated Size Class and Auto Layout in the demo. https://github.com/lexrus/LTMorphingLabel/commit/dedfaa673054e371e017a85c1f340c840d3d1ce5

And set a new text in viewDidLoad:
https://github.com/lexrus/LTMorphingLabel/commit/b65a386422b6b261ae40500d921170c5f481638e#diff-7825dcc6b9f4ca74445235a9997d0e37R31
It seems like the alignment is okay.

Could you please try the latest code.

**Comment by skware** [comment]
Hi,
Just tested here and alignment works as expected when the text is set in viewDidLoad.
Thanks for fixing it!

**Comment by lexrus** [comment]
@skware :+1:
