### ISSUE TITLE
IBDesignable attributes not showing in attribute inspector

### ISSUE THREAD

**Issue by quachdev** [lexrus/LTMorphingLabel#84]
The custom LTMorphingLabel do not show up with attributes to set the styling of the text?

Is it all done programatically? 

I installed via carthage.

**Comment by vitalii-tym** [comment]
It looks like a general issue with Xcode and might not be directly related to LTMorphingLabel, because I'm having similar trouble with https://github.com/ElaWorkshop/TagListView and have also seen it with some other framework. 
Both installed using Carthage.
