### ISSUE TITLE
Crash in production

### ISSUE THREAD

**Issue by itchingpixels** [lexrus/LTMorphingLabel#91]
Hi!

We really like this library and started using it in production.
We're using the .scale effect.

http://crashes.to/s/3cdb2e84de8

This is indicates that it is crashing on:
s.draw(in: charRect, withAttributes: [
                    NSFontAttributeName:
                        UIFont.init(name: font.fontName, size: charLimbo.size)!,
                    NSForegroundColorAttributeName:
                        textColor.withAlphaComponent(charLimbo.alpha)
                    ])

Which I'm not sure what to do about exactly. Any thoughts?

**Comment by lexrus** [comment]
I can't figure out what caused this crash according to the stack trace. I just removed some force unwrapping and release a new version. I hope this may solve you problem.

Thanks.

**Comment by itchingpixels** [comment]
Great, thank you! Will update it and release a new version. Will report back when we see the results!

**Comment by itchingpixels** [comment]
I think unfortunately it's still crashing at s.draw.

I caught it:

Assertion failed: (x >= 0 && x < final_bitmap->width), function draw_glyph_bitmap_run_with_compositing, file /BuildRoot/Library/Caches/com.apple.xbs/Sources/Quartz2D_Sim/Quartz2D-1070.22/CoreGraphicsRIP/RIP/RIPContextDrawGlyphs.c, line 424.

![image](https://user-images.githubusercontent.com/5416288/29681724-866f30bc-8900-11e7-9231-f2a9648c6ba4.png)

the character is `s	String	"त"	`, which is in Hindi language.

**Comment by itchingpixels** [comment]
![image](https://user-images.githubusercontent.com/5416288/29682358-a26bfa32-8902-11e7-9cc0-70b0f2689861.png)

**Comment by lexrus** [comment]
I've added a test case for Hindi language. It seems everything works fine.
Could you please give me an array of possible text?

**Comment by Desgard** [comment]
In these datas, it can crash, too.

```swift
static var textArray = [
        "Sepicat",
        "Cat litter",
        "猫砂",
        "猫のごみ",
        "Litière pour chat",
        "Lectica",
        "Katzenstreu",
    ]
```

**Comment by lexrus** [comment]
@Desgard Sorry for this late reply. I just tested this array. No crash.
