### ISSUE TITLE
Gracefully handle if text is nil

### ISSUE THREAD

**Issue by itchingpixels** [lexrus/LTMorphingLabel#92]
Unfortunately there's some legacy code in our app that sets the text property to nil sometimes of a label.
This crashes LTMorphingLabel, would it be possible to gracefully handle nil `text`?
Thank you!

**Comment by itchingpixels** [comment]
Ohh I think this has been fixed in the latest release! 0.5.3, could you please confirm?:)

**Comment by lexrus** [comment]
Um... I can't garantee.
Let me add an UI test case tonight.
