### ISSUE TITLE
error when updating carthage

### ISSUE THREAD

**Issue by BilalBaydoun** [lexrus/LTMorphingLabel#96]
Hi,

I'm facing this issue when updating carthage on xcode 9:

Bilals-MacBook-Pro:hbd bilalbaydoun$ carthage update
*** Fetching LTMorphingLabel
*** Checking out LTMorphingLabel at "0.5.3"
*** xcodebuild output can be found in /var/folders/3g/8zp4tfjx7q50h7wk_yd922040000gn/T/carthage-xcodebuild.jBnpjZ.log
*** Building scheme "LTMorphingLabel_tvOS" in LTMorphingLabelDemo.xcodeproj
Build Failed
	Task failed with exit code 70:
	/usr/bin/xcrun xcodebuild -project /Users/bilalbaydoun/Documents/HBD/Carthage/Checkouts/LTMorphingLabel/LTMorphingLabelDemo.xcodeproj -scheme LTMorphingLabel_tvOS -configuration Release -derivedDataPath /Users/bilalbaydoun/Library/Caches/org.carthage.CarthageKit/DerivedData/9.0_9A235/LTMorphingLabel/0.5.3 -sdk appletvsimulator -destination platform=tvOS\ Simulator,id=C3CEB6C2-1583-41F9-95A8-1D28DA70B7F3 -destination-timeout 3 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES build (launched in /Users/bilalbaydoun/Documents/HBD/Carthage/Checkouts/LTMorphingLabel)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/3g/8zp4tfjx7q50h7wk_yd922040000gn/T/carthage-xcodebuild.jBnpjZ.log

any idea?

Thanks

**Comment by SirWellington** [comment]
Getting the same issue:

```
Build settings from command line:
    CARTHAGE = YES
    CODE_SIGN_IDENTITY = 
    CODE_SIGNING_REQUIRED = NO
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = appletvsimulator11.0

xcodebuild: error: Unable to find a destination matching the provided destination specifier:
		{ platform:tvOS Simulator, id:0DC55632-4F7A-43B0-B083-C0BF814537A8 }

	Ineligible destinations for the "LTMorphingLabel_tvOS" scheme:
		{ platform:tvOS, id:dvtdevice-DVTiOSDevicePlaceholder-appletvos:placeholder, name:Generic tvOS Device }
		{ platform:tvOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-appletvsimulator:placeholder, name:Generic tvOS Simulator Device }
```

**Comment by SirWellington** [comment]
There is something funky going on with the TV_OS build. 
Running this in the command-line fixed things:
```
carthage update --platform "iOS"
```

**Comment by lexrus** [comment]
Fixed in the latest commit. Please try again.
