### ISSUE TITLE
Type of expression is ambiguous without more context!

### ISSUE THREAD

**Issue by AbdulazizAlmohsen** [lexrus/LTMorphingLabel#99]
I tried to add some pods like OneSignal and failed to do it so I deleted OneSignal pod and extensions but suddenly LTMorphingLabel got issues. It used to work perfectly for 2 months but after deleting other pods something strange happened
<img width="757" alt="screen shot 2017-10-01 at 3 31 53 pm" src="https://user-images.githubusercontent.com/18103561/31054611-db1f80ea-a6be-11e7-9573-95a17e231ce9.png">
<img width="609" alt="screen shot 2017-10-01 at 3 32 07 pm" src="https://user-images.githubusercontent.com/18103561/31054612-db746362-a6be-11e7-859d-37f7ab8fa0ec.png">
<img width="754" alt="screen shot 2017-10-01 at 3 33 17 pm" src="https://user-images.githubusercontent.com/18103561/31054613-db773dd0-a6be-11e7-9f7a-19c285a3e7bb.png">

<img width="542" alt="screen shot 2017-10-01 at 3 48 48 pm" src="https://user-images.githubusercontent.com/18103561/31054652-0fb0064e-a6c0-11e7-9186-a096a9c03ebb.png">

my pod file looks like this
```
# Uncomment this line to define a global platform for your project
platform :ios, '10.0'
use_frameworks!

target 'Jaee2' do
# Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Jaee2
pod 'Haneke', '~> 1.0'
pod 'STLocationRequest'
pod 'SwiftyJSON'
pod 'Alamofire', '~> 4.4'
pod 'PasswordTextField'
pod 'SkyFloatingLabelTextField', '~> 3.0'
pod 'SwiftVideoBackground'
pod 'TIPBadgeManager', '~> 0.3.0'
pod 'LTMorphingLabel'
pod 'LocationPickerViewController'

end
```

**Comment by younatics** [comment]
+1

**Comment by lexrus** [comment]
Did you build the project with Xcode 9?

**Comment by AbdulazizAlmohsen** [comment]
Yes using pods

**Comment by kaungzaythu** [comment]
I also encounter this problem.

**Comment by younatics** [comment]
I fount the solution. Use former version of this library. This library already updated to Swift 4.0

**Comment by kaungzaythu** [comment]
@younatics , how can i get the former version ?
Currently in my pod in like following
`pod 'LTMorphingLabel'`

**Comment by younatics** [comment]
make version like this one.
`pod 'Haneke', '~> 1.0'`

**Comment by kaungzaythu** [comment]
@younatics, we are talking about `LTMorphingLabel`, right?

i tried `pod 'LTMorphingLabel', '~> 1.0'` but i cannot solve the issue

**Comment by lexrus** [comment]
@kaungzaythu 
`pod 'LTMorphingLabel', '0.5.3'`

**Comment by lexrus** [comment]
I've created a test project with the following podfile:
```ruby
platform :ios, '10.0'
use_frameworks!
target 'testproject' do
  pod "LTMorphingLabel"
end
```
The workspace compiled this lib without any problem.
The .swift-version file was set to Swift 4.0 so that Xcode could understand the APIs.

**Comment by AbdulazizAlmohsen** [comment]
Thank you. problem solved

**Comment by Jackson-Jack** [comment]
@lexrus I also encountered this problem before, and had fixed by the way that you provider. But I wonder to know why  LTMorphingLabel cannot build in swift 4. Could you found what’s wrong?
